#!/bin/bash
set -euo pipefail

# Sets up a local Supabase dev environment using Docker.
#
# Usage:
#   ./scripts/setup-local.sh
#
# Requires:
#   - Docker running
#   - Supabase CLI installed (brew install supabase/tap/supabase)
#
# What this does:
#   1. Starts local Supabase (Postgres, GoTrue, PostgREST, Studio, etc.)
#   2. Applies migrations and seeds the database
#   3. Writes .env.local with local URLs and keys

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="${SCRIPT_DIR}/.."

cd "$PROJECT_DIR"

# ── Preflight ──
if ! command -v supabase &> /dev/null; then
  echo "Supabase CLI not found."
  echo "Install: brew install supabase/tap/supabase"
  exit 1
fi

if ! docker info &> /dev/null 2>&1; then
  echo "Docker is not running. Start Docker and try again."
  exit 1
fi

# ── Start Supabase ──
echo "Starting local Supabase..."
supabase start

# ── Get local credentials ──
echo ""
echo "Fetching local credentials..."

SUPABASE_URL=$(supabase status --output json | jq -r '.API_URL')
SUPABASE_ANON_KEY=$(supabase status --output json | jq -r '.ANON_KEY')
SUPABASE_SERVICE_ROLE_KEY=$(supabase status --output json | jq -r '.SERVICE_ROLE_KEY')

# ── Write .env.local ──
echo ""
echo "Writing .env.local..."

# Preserve PELOTON_TOKEN_ENCRYPTION_KEY if it exists
EXISTING_ENCRYPTION_KEY=""
if [[ -f "${PROJECT_DIR}/.env.local" ]]; then
  EXISTING_ENCRYPTION_KEY=$(grep '^PELOTON_TOKEN_ENCRYPTION_KEY=' "${PROJECT_DIR}/.env.local" | cut -d= -f2- || true)
fi
ENCRYPTION_KEY="${EXISTING_ENCRYPTION_KEY:-$(openssl rand -base64 32)}"

EXISTING_CRON_SECRET=""
if [[ -f "${PROJECT_DIR}/.env.local" ]]; then
  EXISTING_CRON_SECRET=$(grep '^CRON_SECRET=' "${PROJECT_DIR}/.env.local" | cut -d= -f2- || true)
fi
CRON_SECRET="${EXISTING_CRON_SECRET:-$(openssl rand -base64 32)}"

cat > "${PROJECT_DIR}/.env.local" <<EOF
# Supabase (auto-generated by scripts/setup-local.sh — local Docker)
NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}

# Encryption key for Peloton tokens
PELOTON_TOKEN_ENCRYPTION_KEY=${ENCRYPTION_KEY}

# Peloton API (public values from Peloton's web app)
NEXT_PUBLIC_PELOTON_AUTH0_CLIENT_ID=WVoJxVDdPoFx4RNewvvg6ch2mZ7bwnsM
NEXT_PUBLIC_PELOTON_AUTH0_DOMAIN=auth.onepeloton.com
NEXT_PUBLIC_PELOTON_API_URL=https://api.onepeloton.com

# Cron secret for scheduled jobs
CRON_SECRET=${CRON_SECRET}
EOF

echo ""
echo "Done! Local dev environment ready."
echo ""
echo "  Supabase API:  ${SUPABASE_URL}"
echo "  Studio:        http://127.0.0.1:54323"
echo "  Inbucket:      http://127.0.0.1:54324"
echo ""
echo "  Test accounts:"
echo "    matthew@thekerns.net / testpass123"
echo "    jane@test.dev / testpass123"
echo ""
echo "  Start dev server: npm run dev"
echo "  Stop Supabase:    supabase stop"
echo ""
